#### Feature scaling
: output이 바뀌지 않으며, 처리속도가 좀 더 빨라진다.
- feature(변수)간의 min-max를 맞춰준다.
    - Min-Max Normalization
- Standardization(정규분포화, Z-score Normalization)

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],'B':[103.02,107.26,110.35,114.23,114.68], 'C':['big','small','big','small','small']})
df

       A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

##### Min-Max Normalization

In [4]:
# A를 1~5사이의 값으로 바꿔준다.
df['A'] = (df['A'] - df['A'].min()) / (df['A'].max() - df['A'].min()) * (5 - 1) + 1
df

          A       B      C
0  1.000000  103.02    big
1  4.704874  107.26  small
2  4.741339  110.35    big
3  5.000000  114.23  small
4  4.753981  114.68  small

##### Z-Score Normalization

In [5]:
df['B'] = (df['B'] - df['B'].mean()) / df['B'].std()
df

          A         B      C
0  1.000000 -1.405250    big
1  4.704874 -0.540230  small
2  4.741339  0.090174    big
3  5.000000  0.881749  small
4  4.753981  0.973556  small

##### Feature scaling with sklearn

In [6]:
df = pd.io.parsers.read_csv(
    'https://raw.githubusercontent.com/rasbt/pattern_classification/master/data/wine_data.csv',
     header=None,
     usecols=[0,1,2]
    )

df.columns=['Class label', 'Alcohol', 'Malic acid']

df.head()

   Class label  Alcohol  Malic acid
0            1    14.23        1.71
1            1    13.20        1.78
2            1    13.16        2.36
3            1    14.37        1.95
4            1    13.24        2.59

In [7]:
from sklearn import preprocessing

In [18]:
std_scale = preprocessing.StandardScaler().fit(df[['Alcohol','Malic acid']])
df_std = std_scale.transform(df[['Alcohol','Malic acid']])

minmax_scale = preprocessing.MinMaxScaler(feature_range=(1,5)).fit(df[['Alcohol','Malic acid']])
df_minmax = minmax_scale.transform(df[['Alcohol','Malic acid']])

fit() -> transform() 형태 : labelencoder와 동일

In [19]:
df_std

array([[ 1.51861254, -0.5622498 ],
       [ 0.24628963, -0.49941338],
       [ 0.19687903,  0.02123125],
       [ 1.69154964, -0.34681064],
       [ 0.29570023,  0.22769377],
       [ 1.48155459, -0.51736664],
       [ 1.71625494, -0.4186237 ],
       [ 1.3086175 , -0.16727801],
       [ 2.25977152, -0.62508622],
       [ 1.0615645 , -0.88540853],
       [ 1.3580281 , -0.15830138],
       [ 1.38273339, -0.76871232],
       [ 0.92568536, -0.54429654],
       [ 2.16095032, -0.54429654],
       [ 1.70390229, -0.4186237 ],
       [ 0.77745356, -0.47248348],
       [ 1.60508109, -0.37374054],
       [ 1.02450655, -0.68792264],
       [ 1.46920194, -0.66996938],
       [ 0.78980621,  0.68550197],
       [ 1.3086175 , -0.63406285],
       [-0.08723191,  1.31386618],
       [ 0.87627476, -0.42760033],
       [-0.18605311, -0.66099274],
       [ 0.61686912, -0.47248348],
       [ 0.06099988, -0.25704433],
       [ 0.48098997, -0.50839001],
       [ 0.36981612, -0.55327317],
       [ 1.07391715, -0.3916938 ],
       [ 1.2592069 , -0.58917969],
       [ 0.90098006, -0.75075906],
       [ 0.71569031, -0.60713296],
       [ 0.83921681, -0.45453022],
       [ 0.93803801, -0.72382916],
       [ 0.62922177, -0.48146012],
       [ 0.59216382, -0.47248348],
       [ 0.34511082, -0.62508622],
       [ 0.06099988, -0.61610959],
       [ 0.08570518, -0.75075906],
       [ 1.50625989,  1.48442217],
       [ 0.69098501, -0.5622498 ],
       [ 0.50569527,  1.3497727 ],
       [ 1.0862698 , -0.40067043],
       [ 0.29570023,  1.47544554],
       [ 0.06099988, -0.50839001],
       [ 1.49390724,  1.52930533],
       [ 1.70390229,  1.12535692],
       [ 1.1109751 , -0.58917969],
       [ 1.3580281 , -0.28397422],
       [ 1.1603857 , -0.54429654],
       [ 0.06099988, -0.54429654],
       [ 1.02450655, -0.61610959],
       [ 1.01215391, -0.52634327],
       [ 0.95039066, -0.3916938 ],
       [ 0.91333271, -0.59815632],
       [ 0.69098501, -0.54429654],
       [ 1.50625989, -0.57122643],
       [ 0.35746347, -0.32885738],
       [ 0.88862741, -0.81359548],
       [-0.77898029, -1.25345042],
       [-0.82839089, -1.10982432],
       [-0.44545875, -0.8764319 ],
       [ 0.82686416, -0.97517485],
       [-0.77898029, -1.08289442],
       [-1.02603329, -0.79564222],
       [-0.77898029, -1.01108137],
       [ 0.13511578, -1.190614  ],
       [-0.77898029, -1.0469879 ],
       [ 0.41922672, -1.25345042],
       [-0.97662269, -1.02903463],
       [-0.87780149, -0.65201611],
       [ 1.0615645 , -0.74178243],
       [ 0.60451647, -0.60713296],
       [-0.01311602, -0.59815632],
       [-1.28543893, -1.11880095],
       [-1.65601842, -0.40964706],
       [ 0.03629458, -1.28935695],
       [-1.43367073,  0.49699271],
       [-0.82839089, -1.20856726],
       [-0.37134286,  1.3767026 ],
       [-1.23602833, -1.27140368],
       [-0.34663756, -0.47248348],
       [-1.13720713, -1.08289442],
       [ 0.06099988,  1.36772596],
       [-1.43367073, -1.29833358],
       [-0.4084008 , -1.21754389],
       [-1.03838594, -0.65201611],
       [-1.66837107, -0.59815632],
       [-1.68072372, -0.2480677 ],
       [-1.13720713, -0.90336179],
       [-1.13720713, -0.45453022],
       [-1.23602833, -0.74178243],
       [-0.38369551, -0.72382916],
       [-0.87780149,  0.44313292],
       [-1.70542902, -0.31090412],
       [-0.6554538 , -0.7328058 ],
       [-1.47072867, -0.19420791],
       [-0.87780149, -0.83154874],
       [-0.77898029, -1.13675421],
       [-0.87780149,  0.74833839],
       [-1.13720713, -0.23011443],
       [-0.49486935, -0.89438516],
       [-0.81603824,  0.10202093],
       [-1.45837602, -0.55327317],
       [-0.6060432 , -0.54429654],
       [-0.71721705,  0.19178724],
       [-0.92721209, -0.54429654],
       [-0.34663756, -0.52634327],
       [-0.96427004, -0.93926832],
       [-1.71778167, -0.88540853],
       [-1.90307141,  1.26000639],
       [-0.59369055,  0.08406767],
       [-1.53249192,  0.30848345],
       [-1.96483466, -1.43298305],
       [-1.13720713, -0.849502  ],
       [-2.43423535, -0.74178243],
       [-1.45837602, -0.77768895],
       [-0.71721705, -0.65201611],
       [-0.28487431,  0.98173081],
       [-1.23602833,  0.98173081],
       [-1.91542406,  0.05713777],
       [-1.77954492, -0.25704433],
       [-0.71721705,  1.87939396],
       [ 0.06099988,  3.10919247],
       [-1.39661278,  1.77167438],
       [-1.14955978, -0.15830138],
       [-0.7048644 , -0.72382916],
       [-1.49543397, -0.18523128],
       [-0.77898029, -0.63406285],
       [-1.18661773,  1.76269775],
       [-0.17370046, -0.88540853],
       [-0.14899516,  0.58675903],
       [-0.23546371, -0.02365191],
       [-0.37134286,  1.08945039],
       [-0.6060432 , -0.98415148],
       [-0.49486935,  0.11099756],
       [-0.92721209,  2.13971627],
       [-0.5813379 ,  2.84887015],
       [ 0.60451647,  1.12535692],
       [-0.19840576,  0.55982913],
       [-0.08723191,  0.42517966],
       [ 0.44393202,  0.20076388],
       [ 0.64157442,  0.74833839],
       [ 0.76510091,  2.34617879],
       [-0.92721209,  1.38567923],
       [ 0.19687903,  1.10740365],
       [ 1.0862698 ,  2.42696848],
       [-0.16134781,  2.04097332],
       [ 0.39452142,  0.81117481],
       [ 0.09805783,  1.40363249],
       [ 0.61686912,  0.70345524],
       [-0.26016901,  0.29950682],
       [ 0.13511578, -0.3916938 ],
       [ 0.28334758,  0.8650346 ],
       [-0.51957465, -0.93926832],
       [ 0.20923168,  2.56161795],
       [ 1.0368592 ,  1.60111838],
       [-0.6801591 ,  0.62266555],
       [ 1.65449169, -0.58917969],
       [ 0.59216382, -0.59815632],
       [-0.79133294,  1.34079607],
       [ 0.85156946,  0.82912808],
       [-0.18605311,  0.83810471],
       [-0.05017396,  0.99968408],
       [ 0.96274331,  0.3802965 ],
       [ 0.90098006,  1.81655754],
       [ 0.55510587,  1.22409986],
       [-0.22311106,  0.92787102],
       [ 0.71569031,  0.21871714],
       [ 0.49334262,  2.03199669],
       [-0.98897534,  0.62266555],
       [-0.28487431,  0.04816114],
       [ 1.43214399,  0.15588072],
       [ 0.87627476,  2.974543  ],
       [ 0.49334262,  1.41260912],
       [ 0.33275817,  1.74474449],
       [ 0.20923168,  0.22769377],
       [ 1.39508604,  1.58316512]])

In [20]:
df_minmax

array([[ 4.36842105,  1.76679842],
       [ 3.28421053,  1.82213439],
       [ 3.24210526,  2.28063241],
       [ 4.51578947,  1.95652174],
       [ 3.32631579,  2.46245059],
       [ 4.33684211,  1.80632411],
       [ 4.53684211,  1.89328063],
       [ 4.18947368,  2.11462451],
       [ 5.        ,  1.71146245],
       [ 3.97894737,  1.48221344],
       [ 4.23157895,  2.12252964],
       [ 4.25263158,  1.58498024],
       [ 3.86315789,  1.7826087 ],
       [ 4.91578947,  1.7826087 ],
       [ 4.52631579,  1.89328063],
       [ 3.73684211,  1.8458498 ],
       [ 4.44210526,  1.93280632],
       [ 3.94736842,  1.65612648],
       [ 4.32631579,  1.67193676],
       [ 3.74736842,  2.86561265],
       [ 4.18947368,  1.70355731],
       [ 3.        ,  3.41897233],
       [ 3.82105263,  1.88537549],
       [ 2.91578947,  1.6798419 ],
       [ 3.6       ,  1.8458498 ],
       [ 3.12631579,  2.03557312],
       [ 3.48421053,  1.81422925],
       [ 3.38947368,  1.77470356],
       [ 3.98947368,  1.91699605],
       [ 4.14736842,  1.743083  ],
       [ 3.84210526,  1.60079051],
       [ 3.68421053,  1.72727273],
       [ 3.78947368,  1.86166008],
       [ 3.87368421,  1.62450593],
       [ 3.61052632,  1.83794466],
       [ 3.57894737,  1.8458498 ],
       [ 3.36842105,  1.71146245],
       [ 3.12631579,  1.71936759],
       [ 3.14736842,  1.60079051],
       [ 4.35789474,  3.56916996],
       [ 3.66315789,  1.76679842],
       [ 3.50526316,  3.45059289],
       [ 4.        ,  1.90909091],
       [ 3.32631579,  3.56126482],
       [ 3.12631579,  1.81422925],
       [ 4.34736842,  3.60869565],
       [ 4.52631579,  3.25296443],
       [ 4.02105263,  1.743083  ],
       [ 4.23157895,  2.01185771],
       [ 4.06315789,  1.7826087 ],
       [ 3.12631579,  1.7826087 ],
       [ 3.94736842,  1.71936759],
       [ 3.93684211,  1.79841897],
       [ 3.88421053,  1.91699605],
       [ 3.85263158,  1.73517787],
       [ 3.66315789,  1.7826087 ],
       [ 4.35789474,  1.75889328],
       [ 3.37894737,  1.97233202],
       [ 3.83157895,  1.54545455],
       [ 2.41052632,  1.15810277],
       [ 2.36842105,  1.28458498],
       [ 2.69473684,  1.49011858],
       [ 3.77894737,  1.40316206],
       [ 2.41052632,  1.3083004 ],
       [ 2.2       ,  1.56126482],
       [ 2.41052632,  1.3715415 ],
       [ 3.18947368,  1.21343874],
       [ 2.41052632,  1.33992095],
       [ 3.43157895,  1.15810277],
       [ 2.24210526,  1.35573123],
       [ 2.32631579,  1.68774704],
       [ 3.97894737,  1.60869565],
       [ 3.58947368,  1.72727273],
       [ 3.06315789,  1.73517787],
       [ 1.97894737,  1.27667984],
       [ 1.66315789,  1.90118577],
       [ 3.10526316,  1.12648221],
       [ 1.85263158,  2.69960474],
       [ 2.36842105,  1.19762846],
       [ 2.75789474,  3.4743083 ],
       [ 2.02105263,  1.14229249],
       [ 2.77894737,  1.8458498 ],
       [ 2.10526316,  1.3083004 ],
       [ 3.12631579,  3.46640316],
       [ 1.85263158,  1.11857708],
       [ 2.72631579,  1.18972332],
       [ 2.18947368,  1.68774704],
       [ 1.65263158,  1.73517787],
       [ 1.64210526,  2.04347826],
       [ 2.10526316,  1.46640316],
       [ 2.10526316,  1.86166008],
       [ 2.02105263,  1.60869565],
       [ 2.74736842,  1.62450593],
       [ 2.32631579,  2.65217391],
       [ 1.62105263,  1.98814229],
       [ 2.51578947,  1.61660079],
       [ 1.82105263,  2.09090909],
       [ 2.32631579,  1.52964427],
       [ 2.41052632,  1.26086957],
       [ 2.32631579,  2.92094862],
       [ 2.10526316,  2.05928854],
       [ 2.65263158,  1.4743083 ],
       [ 2.37894737,  2.35177866],
       [ 1.83157895,  1.77470356],
       [ 2.55789474,  1.7826087 ],
       [ 2.46315789,  2.43083004],
       [ 2.28421053,  1.7826087 ],
       [ 2.77894737,  1.79841897],
       [ 2.25263158,  1.43478261],
       [ 1.61052632,  1.48221344],
       [ 1.45263158,  3.3715415 ],
       [ 2.56842105,  2.33596838],
       [ 1.76842105,  2.53359684],
       [ 1.4       ,  1.        ],
       [ 2.10526316,  1.51383399],
       [ 1.        ,  1.60869565],
       [ 1.83157895,  1.5770751 ],
       [ 2.46315789,  1.68774704],
       [ 2.83157895,  3.12648221],
       [ 2.02105263,  3.12648221],
       [ 1.44210526,  2.31225296],
       [ 1.55789474,  2.03557312],
       [ 2.46315789,  3.91699605],
       [ 3.12631579,  5.        ],
       [ 1.88421053,  3.82213439],
       [ 2.09473684,  2.12252964],
       [ 2.47368421,  1.62450593],
       [ 1.8       ,  2.09881423],
       [ 2.41052632,  1.70355731],
       [ 2.06315789,  3.81422925],
       [ 2.92631579,  1.48221344],
       [ 2.94736842,  2.77865613],
       [ 2.87368421,  2.24110672],
       [ 2.75789474,  3.22134387],
       [ 2.55789474,  1.39525692],
       [ 2.65263158,  2.35968379],
       [ 2.28421053,  4.14624506],
       [ 2.57894737,  4.77075099],
       [ 3.58947368,  3.25296443],
       [ 2.90526316,  2.75494071],
       [ 3.        ,  2.63636364],
       [ 3.45263158,  2.43873518],
       [ 3.62105263,  2.92094862],
       [ 3.72631579,  4.32806324],
       [ 2.28421053,  3.48221344],
       [ 3.24210526,  3.23715415],
       [ 4.        ,  4.39920949],
       [ 2.93684211,  4.05928854],
       [ 3.41052632,  2.97628458],
       [ 3.15789474,  3.49802372],
       [ 3.6       ,  2.88142292],
       [ 2.85263158,  2.5256917 ],
       [ 3.18947368,  1.91699605],
       [ 3.31578947,  3.02371542],
       [ 2.63157895,  1.43478261],
       [ 3.25263158,  4.51778656],
       [ 3.95789474,  3.67193676],
       [ 2.49473684,  2.81027668],
       [ 4.48421053,  1.743083  ],
       [ 3.57894737,  1.73517787],
       [ 2.4       ,  3.44268775],
       [ 3.8       ,  2.99209486],
       [ 2.91578947,  3.        ],
       [ 3.03157895,  3.14229249],
       [ 3.89473684,  2.59683794],
       [ 3.84210526,  3.86166008],
       [ 3.54736842,  3.33992095],
       [ 2.88421053,  3.07905138],
       [ 3.68421053,  2.45454545],
       [ 3.49473684,  4.0513834 ],
       [ 2.23157895,  2.81027668],
       [ 2.83157895,  2.30434783],
       [ 4.29473684,  2.39920949],
       [ 3.82105263,  4.88142292],
       [ 3.49473684,  3.50592885],
       [ 3.35789474,  3.79841897],
       [ 3.25263158,  2.46245059],
       [ 4.26315789,  3.65612648]])